version: "3.9"

volumes:
 pg_project:

services:
 redis:
  image: redis:alpine
 db:
  image: postgres
  volumes:
   - pg_project:/var/lib/postgresql/data 
  env_file:
   - ./variables.env
 web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
   - .:/code
  ports:
   - "8000:8000"
  env_file:
   - ./variables.env
  depends_on:
   - celery
 celery:
  build: .
  command: celery -A stasj worker
  volumes:
   - .:/code
  links:
   - redis
  env_file:
   - ./variables.env
  depends_on:
   - redis
